### ISSUE TITLE
GDCdownload error

### ISSUE THREAD

**Issue by jw156605** [BioinformaticsFMRP/TCGAbiolinks#23]
I'm getting an inexplicable error when I try to download data. See code and output below.
```{r}
> query <- GDCquery(project = "TCGA-OV",data.category = "Gene expression",platform = "Illumina HiSeq",legacy = TRUE)
```
Accessing GDC. This might take a while...
```{r}
> GDCdownload(query)
```
trying URL 'https://gdc.nci.nih.gov//files/public/file/gdc-client_v1.0.1-windows-x64.zip'
Content type 'application/zip' length 8592060 bytes (8.2 MB)
downloaded 8.2 MB

Error in if (bytes < unit) return(paste0(bytes + " B")) : 
  missing value where TRUE/FALSE needed

Any help is much appreciated.
Thanks,
Josh

**Comment by tiagochst** [comment]
Hi Josh,
I fixed that bug two weeks ago. Please, could you try the last version?

devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")

**Comment by jw156605** [comment]
I still get the same error after updating to the latest version.

```{r}
> sessionInfo()
```
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] TCGAbiolinks_2.1.6

```{r}
query <- GDCquery(project = "TCGA-OV",data.category = "Gene expression",platform = "Illumina HiSeq",legacy = TRUE)
```
Accessing GDC. This might take a while...
Warning: there are more than one file for the same case. Please verify query results.
```{r}
> GDCdownload(query)
```
Error in if (bytes < unit) return(paste0(bytes + " B")) : 
  missing value where TRUE/FALSE needed

**Comment by tiagochst** [comment]
I fixed it. However, your search will download all gene expression data
> table(query$results[[1]]$data_type)

     Exon junction quantification               Exon quantification    Gene expression quantification Isoform expression quantification 
                             1159                              1159                              1468                               618 
        miRNA gene quantification      miRNA isoform quantification 
                             1466                              1466 

It is more than 27Gb data. Probably the download will fail. Either use method = "client" or you should make your query more restrictive by using for example the data.type argument in GDCquery.
