### ISSUE TITLE
can't install TCGAbiolinks

### ISSUE THREAD

**Issue by Taylor95** [BioinformaticsFMRP/TCGAbiolinks#328]
Hi, I am new to TCGAbiolinks and got some errors during installing the package.
R version is 3.6.1
Here's the erro:
``Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  cannot open the connection
`Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  cannot open the connection
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 6041600 != reported length 6052944
2: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 8663040 != reported length 14372143
3: In unzip(zipname, exdir = dest) : error 1 in extracting from zip file
4: In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
  cannot open compressed file 'ShortRead/DESCRIPTION', probable reason 'No such file or directory'`

Then I tried the command:
`BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")`

and got an error again:
`Bioconductor version 3.9 (BiocManager 1.30.4), R 3.6.1 (2019-07-05)
Installing github package(s) 'BioinformaticsFMRP/TCGAbiolinks'
Error: Failed to install 'unknown package' from GitHub:
  cannot open URL 'https://api.github.com/repos/BioinformaticsFMRP/TCGAbiolinks/contents/DESCRIPTION?ref=master'`

Would anyone help me solve this?
Thanks!

**Comment by tiagochst** [comment]
Hi @Taylor95 ,

Are you using Windows ?  I was reading an old post stackoverflow.
https://stackoverflow.com/questions/27583767/warning-downloaded-length-reported-length-in-installing-packages-from-cran

If you are using Rstudio with windows, can you try instead to install using R instead Rstudio.
Otherwise, did you try downloading the zip file from http://bioconductor.org/packages/TCGAbiolinks/ and doing a local install.

**Comment by Taylor95** [comment]
Yes, I tried installing using R and got the similar error. And I also tried installing locally, it said that:
`Warning in install.packages :
  package ‘ComplexHeatmap’ is not available (for R version 3.6.1)`

**Comment by tiagochst** [comment]
You will need to update the package. This probelm was solved recently.
Does the command `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")` works for you?

**Comment by Taylor95** [comment]
> You will need to update the package. This probelm was solved recently.
> Does the command `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")` works for you?

**Comment by Taylor95** [comment]
> You will need to update the package. This probelm was solved recently.
> Does the command `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")` works for you?

No, I got the erro:

> Bioconductor version 3.9 (BiocManager 1.30.4), R 3.6.1 (2019-07-05)
Installing github package(s) 'BioinformaticsFMRP/TCGAbiolinks'
Downloading GitHub repo BioinformaticsFMRP/TCGAbiolinks@master
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/BioinformaticsFMRP/TCGAbiolinks/tarball/master'

**Comment by Taylor95** [comment]
> You will need to update the package. This probelm was solved recently.
> Does the command `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")` works for you?

No, I got the erro:
`Bioconductor version 3.9 (BiocManager 1.30.4), R 3.6.1 (2019-07-05)
Installing github package(s) 'BioinformaticsFMRP/TCGAbiolinks'
Downloading GitHub repo BioinformaticsFMRP/TCGAbiolinks@master
Error in utils::download.file(url, path, method = method, quiet = quiet, :
cannot open URL 'https://api.github.com/repos/BioinformaticsFMRP/TCGAbiolinks/tarball/master'`

**Comment by Taylor95** [comment]
I tried again. There are no warning messages now, but still having the following message:
`From the 60483 genes we couldn't map 3946`
Does it matter?

**Comment by tiagochst** [comment]
@Taylor95 When we map gene symbols to the coordinates we use the last patched version of the genome (GRCh38.p13). The GDC was normally aligned to old patched version and some of the genes are removed. There was a previous discussion #50. 

You can get all genes by setting `summarizedExepriment` argument to `FALSE` in the GDCprepare function.

**Comment by lquvatexas** [comment]
Because of the error of GDCprepare, I followed the suggestion to try:
BiocManager::install("BioinformaticsFMRP/TCGAbiolinks") in R at Mac. However, I get the errors below, how could I solve this problem? Thanks!


Bioconductor version 3.8 (BiocManager 1.30.4), R 3.5.3 (2019-03-11)
Installing github package(s) 'BioinformaticsFMRP/TCGAbiolinks'
Downloading GitHub repo BioinformaticsFMRP/TCGAbiolinks@master
   checking DESCRIPTION meta-information ..._/z1fjm2dj2rg3brcp_wllr_1r0000gn/T/RtmpvWCHoa/remotes1596c2715a46e/BioinformaticsFMRP-TCGAbiolinks-3fd0bce/DESCRIPTION’ ...
* installing *source* package ‘TCGAbiolinks’ ...
** R
Error in lazyLoadDBinsertVariable(vars[i], from, datafile, ascii, compress,  : 
  (converted from warning) internal error 10 in R_compress3
ERROR: unable to build sysdata DB for package ‘TCGAbiolinks’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/TCGAbiolinks’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/TCGAbiolinks’
Error: Failed to install 'TCGAbiolinks' from GitHub:
  (converted from warning) installation of package ‘/var/folders/9_/z1fjm2dj2rg3brcp_wllr_1r0000gn/T//RtmpvWCHoa/file1596c13fc9a49/TCGAbiolinks_2.13.6.tar.gz’ had non-zero exit status

**Comment by tiagochst** [comment]
Please, could you try installing with:

withr::with_envvar(c(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"),
  remotes::install_github('BioinformaticsFMRP/TCGAbiolinks')
)

**Comment by lquvatexas** [comment]
I tried 
withr::with_envvar(c(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"),
  remotes::install_github('BioinformaticsFMRP/TCGAbiolinks')
). It installed successfully, however, when I reload TCGAbiolinks, the GDCprepare error is still there showing"Downloading genome information (try:0) Using: Human genes (GRCh38.p12)
Error: $ operator is invalid for atomic vectors" 
Do you have any thoughts?
Thanks,

**Comment by tiagochst** [comment]
Did you update biomart?

https://bioconductor.org/packages/biomaRt/

Em 11 de set de 2019, à(s) 17:39, Lin(Connor) Qiu <notifications@github.com> escreveu:

**Comment by lquvatexas** [comment]
It worked after I restart R. Thank you very much! Another question is how can I get the actual gene name after TCGAanalyze_Preprocessing? Now, I have the matrices for different gene ID under different samples, how could I get the actual gene name for "ENSG00000000003" and others ENSG0000...,etc? Thank you!

**Comment by tiagochst** [comment]
You can use [biomaRt](http://bioconductor.org/packages/biomaRt/) to get the information or the follwing internal function that uses it `TCGAbiolinks:::get.GRCh.bioMart(genome = "hg38")`

<img width="525" alt="Screen Shot 2019-09-13 at 5 49 48 PM" src="https://user-images.githubusercontent.com/145529/64893975-e76d3d80-d64e-11e9-958b-545f58f9c58c.png">

**Comment by lquvatexas** [comment]
Thanks. And when I use the following query to download miRNA:

query.miR <- GDCquery(project = CancerProject, 
+                   data.category = "Gene expression",
+                   data.type = "miRNA gene quantification",
+                   file.type = "hg19.mirna",
+                   legacy = TRUE)

I got the errors below: 

|Files                                                                |
|:--------------------------------------------------------------------|
|TCGA-3C-AAAU-01A-11R-A41G-13.hg19.mirbase20.mirna.quantification.txt |
|TCGA-3C-AAAU-01A-11R-A41G-13.mirna.quantification.txt                |
|TCGA-3C-AALI-01A-11R-A41G-13.hg19.mirbase20.mirna.quantification.txt |
|TCGA-3C-AALI-01A-11R-A41G-13.mirna.quantification.txt                |
|TCGA-3C-AALJ-01A-31R-A41G-13.hg19.mirbase20.mirna.quantification.txt |
|TCGA-3C-AALJ-01A-31R-A41G-13.mirna.quantification.txt                |
|TCGA-3C-AALK-01A-11R-A41G-13.hg19.mirbase20.mirna.quantification.txt |
|TCGA-3C-AALK-01A-11R-A41G-13.mirna.quantification.txt                |
|TCGA-4H-AAAK-01A-12R-A41G-13.hg19.mirbase20.mirna.quantification.txt |
|TCGA-4H-AAAK-01A-12R-A41G-13.mirna.quantification.txt                |
Error in GDCquery(project = CancerProject, data.category = "Gene expression",  : 
  We were not able to filter using this file type. Examples of available files are above. Please check the vignette for possible entries
Do you know what's the problem there?

**Comment by sunsong95** [comment]
hi，@lquvatexas 
I met the same error with you, did you find a solve method to finish it ?

**Comment by tiagochst** [comment]
@sunsong95 I just fixed. Could you update from github with `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")`

**Comment by sunsong95** [comment]
@tiagochst ，I update TCGAbiolinks by command BiocManager::install("BioinformaticsFMRP/TCGAbiolinks"), but this error is not solved. Here is the error:

--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg19
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-BRCA
--------------------
oo Filtering results
--------------------
ooo By data.type
ooo By file.type


|Files                                                                |
|:--------------------------------------------------------------------|
|TCGA-3C-AAAU-01A-11R-A41G-13.hg19.mirbase20.mirna.quantification.txt |
|TCGA-3C-AAAU-01A-11R-A41G-13.mirna.quantification.txt                |
|TCGA-3C-AALI-01A-11R-A41G-13.hg19.mirbase20.mirna.quantification.txt |
|TCGA-3C-AALI-01A-11R-A41G-13.mirna.quantification.txt                |
|TCGA-3C-AALJ-01A-31R-A41G-13.hg19.mirbase20.mirna.quantification.txt |
|TCGA-3C-AALJ-01A-31R-A41G-13.mirna.quantification.txt                |
|TCGA-3C-AALK-01A-11R-A41G-13.hg19.mirbase20.mirna.quantification.txt |
|TCGA-3C-AALK-01A-11R-A41G-13.mirna.quantification.txt                |
|TCGA-4H-AAAK-01A-12R-A41G-13.hg19.mirbase20.mirna.quantification.txt |
|TCGA-4H-AAAK-01A-12R-A41G-13.mirna.quantification.txt                |
Error in GDCquery(project = CancerProject, data.category = "Gene expression",  : 
  We were not able to filter using this file type. Examples of available files are above. Please check the vignette for possible entries

**Comment by tiagochst** [comment]
@sunsong95 http://rpubs.com/tiagochst/TCGAbiolinks_legacy_miRNA_filter
For BRCA the options are mirna, and hg19.mirbase20.mirna

**Comment by sunsong95** [comment]
@tiagochst ，thank you！so "miRNA expression data: Downstream analysis BRCA" should be updated in site http://www.bioconductor.org/packages/devel/bioc/vignettes/TCGAbiolinks/inst/doc/analysis.html

**Comment by sunsong95** [comment]
@tiagochst ，hi，one more question. My project is TCGA-SKCM, and I got a error when run GDCprepare.
this is my query and command:
```
>query <- GDCquery(project = "TCGA-SKCM",
                  data.category = "Transcriptome Profiling",
                  data.type = "Gene Expression Quantification", 
                  workflow.type = "HTSeq - Counts",
                  experimental.strategy = "RNA-Seq")

>GDCdownload(query = query, directory = DataDirectory)

>dataPrep <- GDCprepare(query = query, 
                       save = TRUE, 
                       directory =  DataDirectory,
                       save.filename = FileNameData)
```
I got this error, and it shows "All samples have been already downloaded", so what is the problem?

```
Downloading data for project TCGA-SKCM
Of the 104 files for download 104 already exist.
All samples have been already downloaded
> 
> #extract data to R
> dataPrep <- GDCprepare(query = queryDown, 
+                        save = TRUE, 
+                        directory =  DataDirectory,
+                        save.filename = FileNameData)
|=====================================================================|100%                      Completed after 6 s 
Starting to add information to samples
 => Add clinical information to samples
 => Adding TCGA molecular information from marker papers
 => Information will have prefix 'paper_' 
skcm subtype information from:doi:10.1016/j.cell.2015.05.044
Error in xj[i] : invalid subscript type 'list'
```

**Comment by jianguozhouzunyimedicaluniversity** [comment]
,,,,
library(TCGAbiolinks) 
library(SummarizedExperiment)
 library(dplyr) 
library(DT)  

TCGA-LUAD_RNA_HTSeq_FPKM_UQ <- GDCprepare(query, directory = destdir ) \|===============================================================================================================\|100%                      Completed after 47 s  Starting to add information to samples  => Add clinical information to samples Add FFPE information. More information at:  => https://cancergenome.nih.gov/cancersselected/biospeccriteria  => http://gdac.broadinstitute.org/runs/sampleReports/latest/FPPP_FFPE_Cases.html  => Adding subtype information to samples luad subtype information from:doi:10.1038/nature13385 Accessing www.ensembl.org to get gene information Downloading genome information (try:0) Using: Human genes (GRCh38.p13) Cache found From the 60483 genes we couldn't map 3971 Error in TCGA - LUAD_RNA_HTSeq_FPKM_UQ <- GDCprepare(query, directory = destdir) :    object 'TCGA' not found
--
‘’‘
@tiagochst

**Comment by tiagochst** [comment]
@jianguozhouzunyimedicaluniversity Could you send me the complete code, please ?

**Comment by jianguozhouzunyimedicaluniversity** [comment]
####TCGA_LAUD download####
    if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
    if (!requireNamespace("TCGAbiolinks", quietly = TRUE))
      BiocManager::install("TCGAbiolinks")
    BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")
    library(TCGAbiolinks)
    library(SummarizedExperiment)
    library(dplyr)
    library(DT)
    #https://cloud.tencent.com/developer/article/1424598
    ## ----results = 'hide', message=FALSE, warning=FALSE, eval = FALSE--------
    TCGAbiolinks:::getGDCprojects()$project_id
      #####GDCprepare ######
    query <- GDCquery(project = "TCGA-LUAD",
                      data.category = "Transcriptome Profiling",
                      data.type = "Gene Expression Quantification",
                      workflow.type = "HTSeq - Counts")
      destdir=file.path(getwd()) 
    GDCdownload(query, directory =destdir ) 
    TCGA-LUAD_RNA_Seq_Counts <- GDCprepare(query, directory = destdir )

**Comment by tiagochst** [comment]
@jianguozhouzunyimedicaluniversity Thanks for the code. The problem is that you cannot name the object `TCGA-`
`TCGA-LUAD_RNA_Seq_Counts <- GDCprepare(query, directory = destdir )` has to be something like 
`TCGA_LUAD_RNA_Seq_Counts <- GDCprepare(query, directory = destdir )`

**Comment by jianguozhouzunyimedicaluniversity** [comment]
get it ! thanks!!

**Comment by FionaTJ** [comment]
“From the 60483 genes we couldn't map 3971”
I want to know if you solve this problem? How you do it? I have the same problem with you.

**Comment by sunsong95** [comment]
@FionaTJ well，I think it‘s not a problem，and it’s normal that some genes can‘t map to Ref gene

**Comment by sunsong95** [comment]
@tiagochst I asked you a question before and I tried to solve it, but it didn't work out. Hope you can help me or give me some advice. This is my script:
```
 CancerProject<- "TCGA-BRCA"
 DataDirectory <- paste0("D:/project/newTCGA/download/GDC/",gsub("-","_",CancerProject))
 FileNameData <- paste0(DataDirectory, "_","HTSeq_Counts",".rda")
 query <- GDCquery(project = CancerProject,
                    data.category = "Transcriptome Profiling",
                    data.type = "Gene Expression Quantification", 
                    workflow.type = "HTSeq - Counts")
 samplesDown <- getResults(query,cols=c("cases"))
 dataSmTP <- TCGAquery_SampleTypes(barcode = samplesDown,
                                    typesample = "TP")
 dataSmNT <- TCGAquery_SampleTypes(barcode = samplesDown,
                                    typesample = "NT") 
 dataSmTP_short <- dataSmTP
 dataSmNT_short <- dataSmNT
 queryDown <- GDCquery(project = CancerProject, 
                          data.category = "Transcriptome Profiling",
                          data.type = "Gene Expression Quantification", 
                          workflow.type = "HTSeq - Counts", 
                          barcode = c(dataSmTP_short, dataSmNT_short))
 GDCdownload(query = queryDown,
                directory = DataDirectory)    
 dataPrep <- GDCprepare(query = queryDown, 
                           save = TRUE, 
                           directory =  DataDirectory,
                           save.filename = FileNameData)
```

I think my query parameter is correct and I got error in GDCprepare(), the error is :
```
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg38
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-BRCA
--------------------
oo Filtering results
--------------------
ooo By data.type
ooo By workflow.type
----------------
oo Checking data
----------------
ooo Check if there are duplicated cases
ooo Check if there results for the query
-------------------
o Preparing output
-------------------
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg38
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-BRCA
--------------------
oo Filtering results
--------------------
ooo By data.type
ooo By workflow.type
ooo By barcode
----------------
oo Checking data
----------------
ooo Check if there are duplicated cases
ooo Check if there results for the query
-------------------
o Preparing output
-------------------
Downloading data for project TCGA-BRCA
GDCdownload will download 1215 files. A total of 308.972096 MB
Downloading as: Mon_Dec_16_15_00_29_2019.tar.gz
|=====================================================================|100%                      Completed after 2 m 
Starting to add information to samples
 => Add clinical information to samples
 => Adding TCGA molecular information from marker papers
 => Information will have prefix 'paper_' 
brca subtype information from:doi.org/10.1016/j.ccell.2018.03.014
Error in xj[i] : invalid subscript type 'list'
```
Thank you!

**Comment by HUSAIN23** [comment]
i tried to run TCGAbiolinks GUI ,i downloaded data drom menu GET GDC data and i select file from directory to analyze clinical analysis adn clicked on generate survival plot but it shows that Aesthetics can not vary with a ribbon

**Comment by tiagochst** [comment]
Hi,

Lately, I am not having a lot of time to give support to the packages. And
when I have time I am using it mainly for ELMER and TCGAbiolinks.
I am not sure when I will have time to fix the GUI. Probably it will take
some months.

Sorry for that,
Tiago

**Comment by SerifatAdebola** [comment]
Can I query with caseID instead of projects?

**Comment by tiagochst** [comment]
@SerifatAdebola Not with TCGAbiolinks. Maybe you should check: [GenomicDataCommons](https://www.bioconductor.org/packages/release/bioc/vignettes/GenomicDataCommons/inst/doc/overview.html)
