### ISSUE TITLE
GDCquery_clinic ERROR

### ISSUE THREAD

**Issue by 42kuroniko** [BioinformaticsFMRP/TCGAbiolinks#597]
I try to download ALL the projects of TCGA mRNA and clinical files, but I went wrong with downsides codes, what should I do to correct the codes?
```
clinical <- GDCquery_clinic(project = 'TCGA-TGCT', type = "clinical")
>Error in GDCquery_clinic(project = "TCGA-TGCT", type = "clinical") : 
  Error: API returned more information
```

**Comment by tiagochst** [comment]
Thanks for the bug, this should be fixed now.

**Comment by ssdy5366228** [comment]
> Thanks for the bug, this should be fixed now.
Hi, I am still encountering the same error using the same code after uninstalling and reinstalling TCGAbiolinks.

**Comment by ssdy5366228** [comment]
> Thanks for the bug, this should be fixed now.

Hi, I am still encountering the same error using the same code after uninstalling and reinstalling TCGAbiolinks.

**Comment by ssdy5366228** [comment]
> I try to download ALL the projects of TCGA mRNA and clinical files, but I went wrong with downsides codes, what should I do to correct the codes?
> 
> ```
> clinical <- GDCquery_clinic(project = 'TCGA-TGCT', type = "clinical")
> >Error in GDCquery_clinic(project = "TCGA-TGCT", type = "clinical") : 
>   Error: API returned more information
> ```

In the source code “clinical.R”, I replaced `treatments$submitter_id <- gsub("_treatment(_[0-9])?","", treatments$submitter_id)` with `treatments$submitter_id <- gsub("_treatment_?[0-9]*", "", treatments$submitter_id)`, it worked, you can try it out.

**Comment by ollemonrasl** [comment]
> Thanks for the bug, this should be fixed now.

Is it possible that I still get the same error? Thanks.
